version: '3'

services:
  app:
    build: ./build
    container_name: spfx
    tty: true
    ports:
      - 4321:4321
      - 5432:5432
      - 35729:35729
    volumes:
      - ./src:/usr/app/spfx
    working_dir: "/usr/app/spfx"